### ISSUE TITLE
Valores no correctos al usar algoritmo (variables Multi-Input)

### ISSUE THREAD

**Issue by DenDenMu** [oscar9/gvpy#1]
Hola, estaba probando gvpy y al querer usar el algoritmo "cluster" ( u otros con mismo INPUT por ejemplo), no consigo hacerlo funcionar con ese INPUT, la descripción dice:
Usage: runalg( "cluster",
                          INPUT[Multiple Input - Band],
                          NUMCLASS[Numerical Value],
                          RESULTLAYER[output raster layer],
                          RESULTTABLE[output table],
                          );
Utilizo por ejemplo:
layer=gvsig_raster.loadRasterLayer("C:....\coche.jpg")
y luego por ejemplo
gvpy.runalg("cluster" , INPUT="layer,1 , layer, 2" , NUMCLASS="3") 

He probado en input todo tipo de combinaciones con comillas, con corchetes etc, pero no funciona y salta "Exception: Not correct values"

¿Como habría que hacer entonces en estos casos?

**Comment by oscar9** [comment]
Buenas,

Es una de las cosas que quedan pendientes. Al principio del readme pongo los tipos de parámetros que acepta, no está preparado el soporte para todos aún. Uno de los pendiente es el tipo "Multi-Input". Intentaré desarrollarlo próximamente y tal vez pronto me echen también una mano en mejorar la librería, y espero tener soporte para todos.

Debería de haberlo especificado mejor, siento las molestias.

**Comment by DenDenMu** [comment]
Pues que pena, era justo en lo que estaba interesado y me veía bien, ojalá lo soporteis pronto.

Gracias por responder.

**Comment by oscar9** [comment]
Buenas de nuevo,

He hecho algunos avances aunque serían de forma provisional pero que en principio deberían de dar soporte a este tipo de variables. Si no te importa enviarme alguna imagen, recorte de ella o que sea similar de lo que necesites, simplemente para asegurarme que funciona y centrarme solo es eso.

Puedes enviarmelo a: masquesig@gmail.com

Un saludo

**Comment by DenDenMu** [comment]
No tengo una imagen concreta, mi idea en principio es probar algo sencillo:
Cargar una imagen (de momento probaba con jpg aunque podría ser tif o cualquier otra que admita tambien al cargarla con loadRasterLayer mismamente o alguna de las tuyas) y luego pasar a esa imagen o capa algunos algoritmos de bandas como el de cluster y otros que hay y obtener las capas etc que den como resultado.

Si necesitas más aclaración dimelo.

Aún no lo has subido cambiado no? Intentaré estar atento para probar el Multi-Input cuando lo subas.

Un saludo y muchas gracias.

**Comment by oscar9** [comment]
Disculpa el retraso, el proyecto se alargó y no había tenido tiempo de actualizar la librería. Ahora está subido y funcionan los multi-input, no he podido comprobar todos pero ya hay un avance. Para capas vectoriales mínimo funciona, falta que le de un tanteo para raster, etc.
